// <auto-generated />
using System;
using GeoLibrary.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoLibrary.Server.Database.Migrations
{
    [DbContext(typeof(GeoLibraryDbContext))]
    [Migration("20260815161813_BookCategories")]
    partial class BookCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.BookCategoryEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories", (string)null);
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.BookDailyViewEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ViewsCount")
                        .HasColumnType("bigint");

                    b.HasKey("BookId", "LibraryId", "Date");

                    b.HasIndex("LibraryId");

                    b.ToTable("BookDailyViews");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("integer");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b184f35-d69e-49ff-ada5-49d7f5f0b231"),
                            Name = "Narrativa",
                            Slug = "fiction"
                        },
                        new
                        {
                            Id = new Guid("2bd7d3fa-d983-4c7f-874c-459f6ba3988f"),
                            Name = "Fantascienza",
                            Slug = "science-fiction"
                        },
                        new
                        {
                            Id = new Guid("4c86ceb7-77b3-4450-81e5-a6ca7b297721"),
                            Name = "Fantasy",
                            Slug = "fantasy"
                        },
                        new
                        {
                            Id = new Guid("fc74ad2c-70a7-4ac0-bf39-70b545b9e8ba"),
                            Name = "Giallo",
                            Slug = "mystery"
                        },
                        new
                        {
                            Id = new Guid("f6a3b357-9644-4b57-9c9f-54feca152ac7"),
                            Name = "Biografia",
                            Slug = "biography"
                        },
                        new
                        {
                            Id = new Guid("f02b09b5-2e5b-4e65-b5e7-d64ebc8ba119"),
                            Name = "Storia",
                            Slug = "history"
                        },
                        new
                        {
                            Id = new Guid("b9728b09-5beb-4a2a-bbe3-8307a5ebeec3"),
                            Name = "Scienza",
                            Slug = "science"
                        },
                        new
                        {
                            Id = new Guid("18e3f450-e6d9-426a-a346-9be2544624f4"),
                            Name = "Arte",
                            Slug = "art"
                        },
                        new
                        {
                            Id = new Guid("4549113b-348b-4a70-8e77-997ad5236ba4"),
                            Name = "Poesia",
                            Slug = "poetry"
                        },
                        new
                        {
                            Id = new Guid("e31badcc-6021-4f60-b768-13aedad23e60"),
                            Name = "Filosofia",
                            Slug = "philosophy"
                        },
                        new
                        {
                            Id = new Guid("b92335fe-c8ef-46e6-8146-ce1741f68b71"),
                            Name = "Romanzi",
                            Slug = "romance"
                        },
                        new
                        {
                            Id = new Guid("86194ae9-2f73-4d8b-83f4-c58fb4c9f322"),
                            Name = "Thriller",
                            Slug = "thriller"
                        },
                        new
                        {
                            Id = new Guid("9384bd91-3151-41c9-aa11-2bfdbd15f83a"),
                            Name = "Diritto",
                            Slug = "law"
                        },
                        new
                        {
                            Id = new Guid("85e7682b-d147-495c-b1b0-3f550eb896a1"),
                            Name = "Tecnologia",
                            Slug = "technology"
                        });
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.LibraryDailyViewEntity", b =>
                {
                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ViewsCount")
                        .HasColumnType("bigint");

                    b.HasKey("LibraryId", "Date");

                    b.ToTable("LibraryDailyViews");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.LibraryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("UserId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.LoanRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("LoanRequests");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.BookCategoryEntity", b =>
                {
                    b.HasOne("GeoLibrary.Server.Abstractions.Entities.BookEntity", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoLibrary.Server.Abstractions.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.BookDailyViewEntity", b =>
                {
                    b.HasOne("GeoLibrary.Server.Abstractions.Entities.BookEntity", "Book")
                        .WithMany("DailyViews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoLibrary.Server.Abstractions.Entities.LibraryEntity", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.BookEntity", b =>
                {
                    b.HasOne("GeoLibrary.Server.Abstractions.Entities.LibraryEntity", "Library")
                        .WithMany("Books")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.LibraryDailyViewEntity", b =>
                {
                    b.HasOne("GeoLibrary.Server.Abstractions.Entities.LibraryEntity", "LibraryEntity")
                        .WithMany("DailyViews")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryEntity");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.LibraryEntity", b =>
                {
                    b.HasOne("GeoLibrary.Server.Abstractions.Entities.UserEntity", null)
                        .WithMany("Libraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.LoanRequestEntity", b =>
                {
                    b.HasOne("GeoLibrary.Server.Abstractions.Entities.BookEntity", null)
                        .WithMany("Bookings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoLibrary.Server.Abstractions.Entities.UserEntity", null)
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.BookEntity", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("DailyViews");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.LibraryEntity", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("DailyViews");
                });

            modelBuilder.Entity("GeoLibrary.Server.Abstractions.Entities.UserEntity", b =>
                {
                    b.Navigation("Libraries");

                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
